---
- name: Test Machine Credentials
  hosts: all
  gather_facts: false
  tasks:
    - name: Ping target hosts
      ansible.builtin.ping:

    - name: Verify remote user
      ansible.builtin.command: whoami
      register: whoami_output

    - name: Display user
      ansible.builtin.debug:
        var: whoami_output.stdout
